### ISSUE TITLE
Bots not connecting

### ISSUE THREAD

**Issue by CrypticKingJoe** [zettabithf/LiteHTTP#1]
So I ran on my self and its not connecting to the CP any reason why?

**Comment by zettabithf** [comment]
This issue has been resolved in commit: [f09128a8e8b856cdcc740254c496a05daac3a774](https://github.com/zettabithf/LiteHTTP/commit/f09128a8e8b856cdcc740254c496a05daac3a774)

The issue was that some encrypted data passed to the panel was being handled as URL encoded characters, thus breaking the decryption routine because it was then considered invalid/incomplete data.
